// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTEoF5UyLy8ByKVdJONVExoSdwDvxv9tU',
    appId: '1:65140272990:web:b5aea465e2e41c743729cf',
    messagingSenderId: '65140272990',
    projectId: 'jood-project-01',
    authDomain: 'jood-project-01.firebaseapp.com',
    storageBucket: 'jood-project-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjcsDYhVa9WizLECWqBwdv0zuZwVW04JM',
    appId: '1:65140272990:android:86a697f6d950c2123729cf',
    messagingSenderId: '65140272990',
    projectId: 'jood-project-01',
    storageBucket: 'jood-project-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUp1P7MyazKew0pRHGU0O9eEt71u9CC84',
    appId: '1:65140272990:ios:39c7aaa5a8ecb0433729cf',
    messagingSenderId: '65140272990',
    projectId: 'jood-project-01',
    storageBucket: 'jood-project-01.firebasestorage.app',
    iosBundleId: 'com.example.jood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUp1P7MyazKew0pRHGU0O9eEt71u9CC84',
    appId: '1:65140272990:ios:39c7aaa5a8ecb0433729cf',
    messagingSenderId: '65140272990',
    projectId: 'jood-project-01',
    storageBucket: 'jood-project-01.firebasestorage.app',
    iosBundleId: 'com.example.jood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTEoF5UyLy8ByKVdJONVExoSdwDvxv9tU',
    appId: '1:65140272990:web:fda536160cc2fa923729cf',
    messagingSenderId: '65140272990',
    projectId: 'jood-project-01',
    authDomain: 'jood-project-01.firebaseapp.com',
    storageBucket: 'jood-project-01.firebasestorage.app',
  );
}
