// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkdDomSxA2w9mM45VmApjtgp1ZElgrur8',
    appId: '1:1062420615326:web:0dba1e67acd84096c02b8f',
    messagingSenderId: '1062420615326',
    projectId: 'joodapp-3051e',
    authDomain: 'joodapp-3051e.firebaseapp.com',
    storageBucket: 'joodapp-3051e.firebasestorage.app',
    measurementId: 'G-ZSD1JZDXWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-_TTbFpZ3SQMiqjHhxvTs9LBe-laNjs',
    appId: '1:1062420615326:android:4bab19e5c9b20aefc02b8f',
    messagingSenderId: '1062420615326',
    projectId: 'joodapp-3051e',
    storageBucket: 'joodapp-3051e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtInlt77LsWRi1cIE-_1AGSXOVLIeXM5A',
    appId: '1:1062420615326:ios:f70d527ac8281c8bc02b8f',
    messagingSenderId: '1062420615326',
    projectId: 'joodapp-3051e',
    storageBucket: 'joodapp-3051e.firebasestorage.app',
    iosBundleId: 'com.jood.offers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtInlt77LsWRi1cIE-_1AGSXOVLIeXM5A',
    appId: '1:1062420615326:ios:ff299e7341cd965cc02b8f',
    messagingSenderId: '1062420615326',
    projectId: 'joodapp-3051e',
    storageBucket: 'joodapp-3051e.firebasestorage.app',
    iosBundleId: 'com.example.jood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkdDomSxA2w9mM45VmApjtgp1ZElgrur8',
    appId: '1:1062420615326:web:243cee107d695972c02b8f',
    messagingSenderId: '1062420615326',
    projectId: 'joodapp-3051e',
    authDomain: 'joodapp-3051e.firebaseapp.com',
    storageBucket: 'joodapp-3051e.firebasestorage.app',
    measurementId: 'G-9Z0MZR78BC',
  );

}